services:
#  web:
#    image: nginx
#    volumes:
#      - ./nginx/nginx.conf:/tmp/nginx.conf
#    environment:
#      - FLASK_SERVER_ADDR=backend:9091
#    command: /bin/bash -c "envsubst < /tmp/nginx.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
#    ports:
#      - 80:80
#    depends_on:
#      - backend
#
#  backend:
#    build:
#      context: flask
#      target: dev-envs
#    stop_signal: SIGINT
#    environment:
#      - FLASK_SERVER_PORT=9091
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock
#    depends_on:
#      - mongo

#  backend:
#    build:
#      context: back-end
#    stop_signal: SIGINT
#    ports:
#      - 80:80
#    depends_on:
#      - mongo
#      - elasticsearch

  mongo:
    image: mongo
    ports:
      - "27017:27017" # DEVELOPMENT ONLY
    expose:
      - "27017"
    volumes:
      - mongo-db:/data/db

  elasticsearch:
    build:
      context: elasticsearch
      dockerfile: Dockerfile
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200" # DEVELOPMENT ONLY
    expose:
      - "9200"
    volumes:
      - es-db:/usr/share/elasticsearch/data

volumes:
    mongo-db:
    es-db:

